<?php
//Set page title
$this->headTitle('Application');

// Get the base url, so our application does not need to be at the root location.
$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();

// Append script at the end of the page, like it should
$this->headScript()->appendFile($baseUrl . '/javascripts/index/requiredselect.js');
?>
<div class="row">
	<div class="twelve columns">
		<h4>Application</h4>
		<p>Select the application you want to create a snapshot of.</p>
	</div>
</div>
<form method="POST" action="<?php echo $this->url(array('module' => 'default', 'controller' => 'snapshot', 'action' => 'application'), null, true); ?>">
	<div class="row">
		<div class="twelve columns">
			<label>Application</label>
			<select id="required" name="instance" class="twelve columns">
				<option value="">Select an application&hellip;</option>
				<?php foreach ($this->instances as $instance): ?>
					<option <?php echo ($instance->id == $this->selectedInstance) ? 'selected="selected" ' : ''; ?>value="<?php echo $this->escape($instance->id); ?>"><?php echo $this->escape($instance->box()->url); ?></option>
				<?php endforeach; ?>
			</select>
		</div>
	</div>
	<div class="row nudgedown">
		<div class="six columns" align="left">
			<span class="has-tip tip-top" title="Select a different server"><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'snapshot', 'action' => 'index'), null, false); ?>" class="button">&Lt; Back</a></span>
		</div>
		<div class="six columns" align="right">
			<span class="has-tip tip-top" title="Select developer"><input type="submit" id="nextbutton" class="secondary disabled button" value="Next &Gt;" /></span>
		</div>
	</div>
</form>