<?php
//Set page title
$this->headTitle('Snapshot');

// Get the base url, so our application does not need to be at the root location.
$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();

// Append script at the end of the page, like it should
$this->headScript()->appendFile($baseUrl . '/javascripts/index/requiredselect.js');
?>
<div class="row">
	<div class="twelve columns">
		<h4>Snapshot</h4>
		<p>Create a development snapshot of an application.</p>
	</div>
</div>
<form method="POST" action="<?php echo $this->url(array('module' => 'default', 'controller' => 'snapshot', 'action' => 'index'), null, true); ?>">
	<div class="row">
		<div class="twelve columns">
			<label>Server</label>
			<select id="required" name="server" class="twelve columns">
				<option value="">Select a server&hellip;</option>
				<?php foreach ($this->servers as $dev => $server): ?>
					<option <?php echo ($server->id == $this->selectedServer) ? 'selected="selected" ' : '' ;?>value="<?php echo $this->escape($server->id); ?>"><?php echo $this->escape($server->name); ?></option>
				<?php endforeach; ?>
			</select>
		</div>
	</div>
	<div class="row nudgedown">
		<div class="six columns" align="left">
			<span class="has-tip tip-top" title="Select a different server"><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'index', 'action' => 'index'), null, true); ?>" class="button">&Lt; Back</a></span>
		</div>
		<div class="six columns" align="right">
			<span class="has-tip tip-top" title="Select developer"><input type="submit" id="nextbutton" class="secondary disabled button" value="Next &Gt;" /></span>
		</div>
	</div>
</form>