<?php
//Set page title
$this->headTitle($this->title);

// Get the base url, so our application does not need to be at the root location.
$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();

// Append script at the end of the page, like it should
$this->headScript()->appendScript('callbackurl = "'.$this->callbackUrl.'";', 'text/javascript', array('noescape' => true));
$this->headScript()->appendScript('failUrl = "'.$this->failUrl.'";', 'text/javascript', array('noescape' => true));
$this->headScript()->appendScript('successUrl = "'.$this->successUrl.'";', 'text/javascript', array('noescape' => true));
$this->headScript()->appendScript('defaultProcessText = "'.$this->defaultProcessText.'";', 'text/javascript', array('noescape' => true));
$this->headScript()->appendScript('name = "'.$this->escape($this->name).'";', 'text/javascript', array('noescape' => true));
$this->headScript()->appendFile($baseUrl . '/javascripts/snapshot/progress.js');
?>
<div class="row">
	<div class="twelve columns">
		<h4><?php echo $this->escape($this->title); ?>&hellip;</h4>
		<p id="member"><?php echo $this->escape($this->text); ?></p>
	</div>
</div>
<div class="row">
	<div class="twelve columns">
		<div class="progress twelve"><span id="progressbar" class="animeter" style="width: 0%"></span></div>
		<p id="progresstext"><?php echo $this->escape($this->initialProgressText); ?>&hellip;</p>
	</div>
</div>
<?php
$url = Zend_Controller_Front::getInstance()->getRequest()->getRequestUri();
?>
<form method="POST" action="<?php echo $this->escape($url); ?>">
	<div class="row nudgedown">
		<div class="four columns" align="left">
			<span class="has-tip tip-top" title="Sorry, a process cannot be stopped."><a class="secondary disabled button">&Lt; STOP!</a></span>
		</div>
		<div class="four columns" align="center">
			<span class="debug has-tip tip-top" title="Debug mode." <?php echo ($this->debugMode > 0) ? '' : 'style="display:none"'; ?>><input class="debug" type="submit" name="restart" class="secondary disabled button" value="Restart" <?php echo ($this->debugMode > 0) ? '' : 'style="display:none"'; ?>/></span>
		</div>
		<div class="four columns" align="right">
			<span class="has-tip tip-top" title="Have patience, young padawan&hellip;"><input id="nextButton" type="submit" name="next" class="secondary disabled button" value="Next &Gt;" /><a id="nextLink" style="display:none" class="secondary disabled button">Next &Gt;</a></span>
		</div>
	</div>
</form>
