<?php
//Set page title
$this->headTitle('Team');

// Get the base url, so our application does not need to be at the root location.
$baseUrl = Zend_Controller_Front::getInstance()->getBaseUrl();

// Append script at the end of the page, like it should
$this->headScript()->appendFile($baseUrl . '/javascripts/index/requiredselect.js');
?>
<div class="row">
	<div class="twelve columns">
		<h4>Team</h4>
		<p>Select all team members that wish to have a snapshot of this website or application.</p>
	</div>
</div>
<form method="POST" action="<?php echo $this->url(array('module' => 'default', 'controller' => 'snapshot', 'action' => 'target'), null, true); ?>">
	<div class="row">
		<div class="twelve columns">
			<label>Team members</label>
			<?php foreach ($this->team as $id => $member): ?>
			<label for="team-<?php echo $this->escape($id); ?>"><input type="checkbox" name="team[]" id="team-<?php echo $this->escape($id); ?>" value="<?php echo $this->escape($id); ?>" <?php echo (in_array($id, $this->selectedTeam)) ? 'selected="selected" ' : '' ;?>> <?php echo $this->escape(ucwords($member)); ?></label>
			<?php endforeach; ?>
		</div>
	</div>
	<div class="row nudgedown">
		<div class="six columns" align="left">
			<span class="has-tip tip-top" title="Select a different application or website"><a href="<?php echo $this->url(array('module' => 'default', 'controller' => 'snapshot', 'action' => 'application', 'server' => $this->serverId), null, true); ?>" class="button">&Lt; Back</a></span>
		</div>
		<div class="six columns" align="right">
			<span class="has-tip tip-top" title="Create snapshot"><input type="submit" id="nextbutton" class="secondary disabled button" value="Create snapshot &Gt;" /></span>
		</div>
	</div>
</form>